const talks = [
  {
    startTime: "10:00",
    endTime: "11:00",
    title: "AI Agent 基础：构建你的第一个自主代理",
    speakers: ["李静"],
    categories: ["入门", "框架", "实战"],
    duration: 60,
    description: "本讲座将介绍AI Agent的基本概念，并指导您如何使用流行的框架（如LangChain或Auto-GPT）构建一个简单的自主代理。我们将从头开始，逐步完成一个可以执行基本任务的代理。",
  },
  {
    startTime: "11:10",
    endTime: "12:10",
    title: "高级AI Agent：记忆与学习",
    speakers: ["张伟", "王芳"],
    categories: ["高级", "记忆", "学习"],
    duration: 60,
    description: "深入探讨AI Agent如何实现长期记忆和持续学习。我们将讨论向量数据库、知识图谱等技术，并展示如何让您的代理从过去的交互中学习，从而变得更智能。",
  },
  {
    startTime: "12:20",
    endTime: "13:20",
    title: "AI Agent在软件开发中的应用",
    speakers: ["刘强"],
    categories: ["软件开发", "自动化", "DevOps"],
    duration: 60,
    description: "探索AI Agent如何改变软件开发流程。从自动化代码生成、测试用例创建到智能化的DevOps流程，本讲座将展示AI Agent在提高开发效率和质量方面的巨大潜力。",
  },
  {
    type: "break",
    startTime: "13:20",
    endTime: "14:20",
    title: "午餐休息",
    duration: 60,
  },
  {
    startTime: "14:20",
    endTime: "15:20",
    title: "AI Agent的安全与伦理",
    speakers: ["赵敏", "孙悦"],
    categories: ["安全", "伦理", "前沿"],
    duration: 60,
    description: "随着AI Agent变得越来越强大，其安全性和伦理问题也日益突出。本讲座将讨论如何防止代理被滥用、保护用户隐私，以及在设计代理时需要考虑的伦理准则。",
  },
  {
    startTime: "15:30",
    endTime: "16:30",
    title: "多模态AI Agent：结合视觉与语言",
    speakers: ["周平"],
    categories: ["多模态", "视觉", "语言"],
    duration: 60,
    description: "未来的AI Agent将不仅仅局限于文本。本讲座将介绍如何构建能够理解图像、视频和语音的多模态AI Agent，并展示它们在现实世界中的应用，如智能客服和机器人。",
  },
  {
    startTime: "16:40",
    endTime: "17:40",
    title: "圆桌讨论：AI Agent的未来展望",
    speakers: ["全体演讲者"],
    categories: ["未来", "讨论", "社区"],
    duration: 60,
    description: "所有演讲者将齐聚一堂，共同探讨AI Agent的未来发展趋势、面临的挑战以及对社会的影响。欢迎现场观众踊跃提问，与专家们进行深入交流。",
  },
];

module.exports = talks;
